# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'LCEHappySmile' do

pod 'AFNetworking'

pod 'YTKNetwork'

pod 'Mantle'

pod 'MagicalRecord'

pod 'Masonry'

pod 'MJRefresh'

pod 'SDWebImage'

pod 'LCProgressHUD'

end

target 'LCEHappySmileTests' do

end

target 'LCEHappySmileUITests' do

end

