# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'LCEHappySmile' do

pod 'AFNetworking', ‘~>2.5.4'

pod 'Mantle'

pod 'MagicalRecord'

pod 'Masonry'

pod 'MJRefresh'

pod 'SDWebImage'

pod 'LCProgressHUD'

pod 'libextobjc'

end

target 'LCEHappySmileTests' do

pod 'Expecta'

end

target 'LCEHappySmileUITests' do

end

